### ISSUE TITLE
Incompatible with 1.12.2

### ISSUE THREAD

**Issue by tinyds** [chris3105x/EasyPrefix#10]
Using the latest version. Running the command "/ep setup" causes an internal error and seems to break the server- inventories stop being able to be used. Any possibility of compatibility being added to this version? Tested on both Paper and Magma 1.12.2, got the same results.

![cmd_2020-06-16_22-21-32](https://user-images.githubusercontent.com/6227279/84847832-f63eb180-b01f-11ea-923a-222b49c76637.png)

**Comment by chris3105x** [comment]
Thank you!
Fixed. I'll upload the patch soon.

**Comment by tinyds** [comment]
I don't mean to be a bother, but when is it being uploaded?

**Comment by chris3105x** [comment]
I will upload the update in a few hours on SpigotMC.
Thanks for your patience!
