### ISSUE TITLE
[BUG] Not working on 1.8

### ISSUE THREAD

**Issue by AidanTheBandit1** [chris3105x/EasyPrefix#106]
# Details
**Spigot Version:** 
1.8.8 Spigot
*please run `/ep debug` and attach a screenshot*
Plugin wont work
# Describe the bug
The plugin wont startup when the server loads
# Expected behavior

# Screenshots

**Comment by chris3105x** [comment]
> 
> 
> I can't update this server to 1.17 though. This server has to stay on 1.8.8 so 1.8 players can join the PvP servers

There are many resources like ViaVersion and ViaBackwords to enable version support. I'm not very interested in supporting outdated versions.
