### ISSUE TITLE
Loading Skulls Causing Lag

### ISSUE THREAD

**Issue by ijerrychan** [chris3105x/EasyPrefix#12]
It happens on servers that can’t get well connected with Minecraft.net to get skulls (like mine). Could you please make skulls load in a async thread or make it possible to edit icons in the GUI to prevent lagging?

**Comment by chris3105x** [comment]
Please run `/ep debug` and send me a screenshot.

**Comment by ijerrychan** [comment]
![bandicam 2020-06-24 06-41-11-816](https://user-images.githubusercontent.com/53806462/85473567-03dad500-b5e6-11ea-8eb8-809eab334063.jpg)

**Comment by ijerrychan** [comment]
> Please run `/ep debug` and send me a screenshot.

![E9F1AE16-85C6-47EA-9125-BFFCECBCEB35](https://user-images.githubusercontent.com/53806462/85527903-e0dc0f80-b63d-11ea-8d00-a672043a82a9.jpeg)

**Comment by chris3105x** [comment]
Why can't a good connection be made?
I'll try to cache the texture, but I'll not remove them.
Also:
The inventory opens immediately and the icons are gradually loaded, so that won't cause lags at all.
I recommend to allocate more memory to the server (at least 2.5G, or 250 - 300 M per player)

Thank you for helping to improve the program!

Best regards

**Comment by ijerrychan** [comment]
> Why can't a good connection be made?
> I'll try to cache the texture, but I'll not remove them.
> Also:
> The inventory opens immediately and the icons are gradually loaded, so that won't cause lags at all.
> I recommend to allocate more memory to the server (at least 2.5G, or 250 - 300 M per player)
> 
> Thank you for helping to improve the program!
> 
> Best regards

Sry for late reply. I’m from China. So you probably know that the connection problem is basically caused by......national policy(I’m running a server with 8G RAM so it shouldn’t be caused by memory). Most plugins with skulls in GUI cause lag on my server(also the servers in my area). But there are also plugins like slimefun, headsplus that won’t cause any lag. Thank you for looking into this issue. Many authors just ignored me as this doesn’t happen on most servers.
