### ISSUE TITLE
[BUG] Can't use the command : /easyprefix settings (so i can't use the plugin)

### ISSUE THREAD

**Issue by EnzoDLP** [chris3105x/EasyPrefix#124]
# Details
**Spigot Version:** 1.16.5 - Paper 625

![Capture](https://user-images.githubusercontent.com/25169729/144124346-352d1c50-caaf-445d-a00f-438dfadb4b2d.JPG)

# Describe the bug

When me (as OP) or a player type the command, nothing happen except an error sometimes in the console : 
>.... [21:37:18 WARN]: [EasyPrefix] Task #14695 for EasyPrefix v1.8.1 generated an exception
net.minecraft.server.v1_16_R3.CancelledPacketHandleException: null

# Expected behavior

I expected the command to open the GUI for user to select the prefix

**Comment by chris3105x** [comment]
fixed. thank you
