### ISSUE TITLE
Prefix and Suffix Issue

### ISSUE THREAD

**Issue by Ph0l0pp** [chris3105x/EasyPrefix#13]
Hi,

i have a problem with the pre- and suffixes.
My problem is: All prefixes/suffixes are doubble (see pictures).

How can i fix this

Infos:
Version: 1.15.2
![GitHubIssue1](https://user-images.githubusercontent.com/61699413/85563903-1842c000-b62e-11ea-95c4-fe61ad013cf6.png)

**Comment by chris3105x** [comment]
Hey!
Please run `/ep debug` and send me a screenshot

**Comment by Ph0l0pp** [comment]
Here is the output:
![GitHubIssue2](https://user-images.githubusercontent.com/61699413/85572318-2ba55980-b635-11ea-8197-4812bddff5b9.png)

**Comment by chris3105x** [comment]
Thank you!
Does the prefix/suffix contain placeholders?

**Comment by Ph0l0pp** [comment]
no

**Comment by chris3105x** [comment]
Try to restart your server. Doesn't look like a bug, also something like this has never happened before. If it's still not working send me the file `groups.yml`

**Comment by Ph0l0pp** [comment]
ok, i cannot restart the server at this time. I will do it later. (Sorry for my bad english)

**Comment by Ph0l0pp** [comment]
The restart didn't help. I can't send the file but can tell you what's inside.

**Comment by chris3105x** [comment]
I'm sorry to hear that
Delete or rename the current EasyPrefix folder and allow the plugin to create the files again.
Is your server public?

I'm really not sure why this is happening. This has never happened to anyone else before

**Comment by Ph0l0pp** [comment]
My Server is not public (at the moment).

**Comment by Ph0l0pp** [comment]
I will recreate a test Server tomorrow, Athen i will test this again.

**Comment by Ph0l0pp** [comment]
Ok, i recreated the server and the problem/bug isn't fixed. What can i do?

**Comment by chris3105x** [comment]
Please run ´/pl´ and send me the list.
Thank you

**Comment by Ph0l0pp** [comment]
Output from /pl
![GitHubIssue3](https://user-images.githubusercontent.com/61699413/85918362-6809cd00-b862-11ea-8264-c1c158a1d059.png)

**Comment by chris3105x** [comment]
please disable handle-chat in config.yml

**Comment by Ph0l0pp** [comment]
I will try it later because i am not at home.

**Comment by Ph0l0pp** [comment]
Sorry you had to wait that long. Your tip solved the problem. Thank you for your help!
