### ISSUE TITLE
plugin stops working

### ISSUE THREAD

**Issue by Anaton546** [chris3105x/EasyPrefix#14]
The plugin works fine when downloading, but about after half an hour it stops responding to /ep settings and /ep setup, and no one can move item in inventorys. Also before that whenever someone opened /ep settings it doesnt let anyone move items for a second.  No warnings in console.

version: 1.15.2
plugin version: 1.6.5

debug: 
![image](https://user-images.githubusercontent.com/67478887/85921357-7072ff80-b884-11ea-9b8c-279f8c30e81d.png)

**Comment by chris3105x** [comment]
Thank you for your report!
fixed.
I'll upload the fix in some hours to spigotmc
