### ISSUE TITLE
[BUG] Prefix

### ISSUE THREAD

**Issue by PixelBeastHD** [chris3105x/EasyPrefix#149]
# Details
**Spigot Version: 1.16.5** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
The prefixes are only showing in the chat

# Expected behavior
The prefixes to show in tab and above players too

# Screenshots

**Comment by chris3105x** [comment]
EasyPrefix only manages the chat layout. You'll need an additionell plugin to show prefixes and suffixes in the tab view.
