### ISSUE TITLE
[BUG] /ep settings and /ep setup notworking

### ISSUE THREAD

**Issue by LoneDevilX** [chris3105x/EasyPrefix#16]
# Details
**Spigot Version:** 

*please run `/ep debug` and attach a screenshot*
![image](https://user-images.githubusercontent.com/67851836/86525962-7be7ab80-bec0-11ea-8fca-cf46de7cb2d0.png)

# Describe the bug
/ep setup and /ep settings unable to load

# Expected behavior
should be loaded well

# Screenshots
![image](https://user-images.githubusercontent.com/67851836/86525978-99b51080-bec0-11ea-9aa3-0f94fbe203be.png)
![image](https://user-images.githubusercontent.com/67851836/86525985-acc7e080-bec0-11ea-82c0-ecd17d391961.png)

**Comment by Schuttle** [comment]
I am running into the same issue if more info is needed to help debug. Currently, I'm not able to try out the plugin with this error occurring. I hope this can be fixed soon!

**Comment by chris3105x** [comment]
Please attach the  log.
Thank you!

**Comment by AnimationgamesYT** [comment]
![screenshot](https://user-images.githubusercontent.com/64910155/86842761-88077080-c05a-11ea-9c89-8c5b0a97f15c.png)
![screenshot2](https://user-images.githubusercontent.com/64910155/86842766-89d13400-c05a-11ea-9734-eb1f69073470.png)
![DEBUG](https://user-images.githubusercontent.com/64910155/86842847-9d7c9a80-c05a-11ea-81ca-ed1a34cf2f37.png)
Those are screenshots that it doesn't work

**Comment by chris3105x** [comment]
Please try the latest version (1.6.5-R3)

**Comment by LoneDevilX** [comment]
![ep](https://user-images.githubusercontent.com/67851836/87144341-2d7c4780-c2da-11ea-8231-05c38b5f9486.PNG)
It still doesnt work.
![ep 2](https://user-images.githubusercontent.com/67851836/87144391-4553cb80-c2da-11ea-95b3-0504ba78b098.PNG)

**Comment by chris3105x** [comment]
and there is no error in the console?

**Comment by LoneDevilX** [comment]
There only show 'Null' in the console, just like the pictures on the top comment.

**Comment by chris3105x** [comment]
Please delete or rename the main folder from EasyPrefix, so that the files can be regenerated
