### ISSUE TITLE
Console Spam [BUG]

### ISSUE THREAD

**Issue by Beeeff** [chris3105x/EasyPrefix#161]
# Details
**Spigot Version:** 
PaperSpigot-318

*Please run `/ep debug` and attach a screenshot*
![image](https://user-images.githubusercontent.com/48077001/168386080-38d7c98c-14b4-4d71-af53-330c6ba43d14.png)

# Describe the bug
Upon login to the server, the console is met with a spam error. It is so repetitive all other work cannot be completed or seen. Error: https://paste.gg/p/anonymous/d4df250a8a5f43ee8e608bbfa6a9ac5a

# Expected behavior
Not to have this error in console

# Screenshots
![image](https://user-images.githubusercontent.com/48077001/168386435-7319a838-bd52-45d5-84d0-ce944c9331f0.png)

**Comment by chris3105x** [comment]
Hi,
please try version [1.8.3](https://www.spigotmc.org/resources/easyprefix-gui-custom-prefixes-sql-support.44580/history). 

Greetings
