### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Elrol** [chris3105x/EasyPrefix#165]
# Details
**Spigot Version:** 
PaperSpigot 295
![image_2022-05-27_080859450](https://user-images.githubusercontent.com/12816881/170705477-69e5029e-c4cf-4502-ae35-aa04cb1c375d.png)

# Describe the bug
The books in /tags are not showing up as enchanted

# Expected behavior
The title currently equipped being a book with enchants in the /tags menu

# Screenshots
![image_2022-05-27_080757377](https://user-images.githubusercontent.com/12816881/170705314-d94b9f3a-ded5-482c-a36a-4a00d86b5a0d.png)
![image_2022-05-27_080817474](https://user-images.githubusercontent.com/12816881/170705366-428a2ae5-9334-4691-8435-985ab19d0ad6.png)

**Comment by chris3105x** [comment]
Fixed. Thank you
