### ISSUE TITLE
Is there a way to remove Prefix and group from the scoreboard?

### ISSUE THREAD

**Issue by Bluejoy2123** [chris3105x/EasyPrefix#174]
# Details
**Spigot Version: 1.18.2** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
Couldn't remove the group from the Tab Scoreboard.

# Expected behavior
Removed and replaced with other thing aside from EasyPrefix group.

# Screenshots
<img width="1440" alt="ภาพถ่ายหน้าจอ 2565-07-07 เวลา 21 12 37" src="https://user-images.githubusercontent.com/108882616/177794884-3bcfb51b-b134-4164-939d-477da46471b1.png">

**Comment by chris3105x** [comment]
Hey,
this plugin does not manage the scoreboard and tablist. You have to modify your tablist/scoreboard plugin.
