### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bluejoy2123** [chris3105x/EasyPrefix#176]
# Details
**Paper version 386:** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
Can't use any GUI related command except for debug and help after the rejoin, first time that I join, it works but not after the second time.

# Expected behavior
After rejoin, you should be able to use the /ep setup and setting or any other command again.

# Screenshots
<img width="651" alt="ภาพถ่ายหน้าจอ 2565-07-09 เวลา 20 35 22" src="https://user-images.githubusercontent.com/108882616/178108234-cd8b8920-bae8-4523-ba67-4b3616a7adfb.png">

<img width="677" alt="ภาพถ่ายหน้าจอ 2565-07-09 เวลา 20 36 14" src="https://user-images.githubusercontent.com/108882616/178108240-2ec0f21b-adda-49e5-ae36-a8bc8958773f.png">

**Comment by frop1k** [comment]
Hi, I have the same problem, any fix?
