### ISSUE TITLE
[BUG] Bug with Vault and BungeeTabListPlus

### ISSUE THREAD

**Issue by SawJin22** [chris3105x/EasyPrefix#179]
# Details
**Spigot Version:** 
running paper 1.18.2-R0.1-SNAPSHOT

*please run `/ep debug` and attach a screenshot*
![image](https://user-images.githubusercontent.com/25687937/180902321-92b42256-fe80-4cde-9777-57b45d76fd87.png)

# Describe the bug

Currently running into an issue I believe is tied to EasyPrefix and an issue with vault specifically. Throwing constant errors in console while attempting to load in tab.

# Expected behavior

Not to receive constant console spam over a invalid perm node this.perms = null

# Screenshots
![image](https://user-images.githubusercontent.com/25687937/180902395-f3fa8f75-f815-4230-be43-ad17cc525fbd.png)

**Comment by SawJin22** [comment]
Believe it has to do with these areas, https://github.com/chris3105x/EasyPrefix/blob/master/src/main/java/com/christian34/easyprefix/extensions/ChatProvider.java#L25, https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/chat/Chat.java#L951-L953

**Comment by chris3105x** [comment]
Hey,
thank you for reporting this issue.  Although the plugin has nothing to do with permissions, Vault requires an additional permission provider, therefore I hooked it into the registered permission system (which is LuckPerms in your case).
I'll upload the bugfix in the next couple of hours.

Greetings,
chris

**Comment by chris3105x** [comment]
https://github.com/chris3105x/EasyPrefix/releases/tag/1.8.5

please try this version
