### ISSUE TITLE
[BUG] Placeholders Not Registering

### ISSUE THREAD

**Issue by EnderGamingFilms** [chris3105x/EasyPrefix#18]
# Details
**Spigot Version:** 1.12.2

*please run `/ep debug` and attach a screenshot*
![](https://user-images.githubusercontent.com/25815579/87821644-04e9d580-c825-11ea-954b-76d0783e4770.png)

# Describe the bug
I use ChatControl for handling chat and the placeholders work on my 1.15 but not my queue server.
![](https://user-images.githubusercontent.com/25815579/87821624-f8657d00-c824-11ea-9886-5ed08c27f681.png)

# Expected behavior
![](https://user-images.githubusercontent.com/25815579/87821698-22b73a80-c825-11ea-9ce9-6f8491e240f0.png)

# Screenshots
![](https://user-images.githubusercontent.com/25815579/87821870-6447e580-c825-11ea-8030-f74994c9d020.png)

**Comment by chris3105x** [comment]
Don't use parentheses. Try %ep_user_prefix%

**Comment by EnderGamingFilms** [comment]
That's not it. ChatControl handles external placeholders using {} instead of %%. The chat works perfectly fine on my main server.

**Comment by chris3105x** [comment]
Please try this version https://github.com/chris3105x/EasyPrefix/raw/master/download/EasyPrefix%201.6.6-ALPHA.jar
Also please try it with %%.

If it still doesn't work afterwards, please enable Debug in `plugins/ChatControl/settings.yml` and write something in the chat. A debug information should appear in the console.

Thank you!

**Comment by EnderGamingFilms** [comment]
I didn't try the %%, that version of the plugin did fix it however 🙂

**Comment by chris3105x** [comment]
Awesome!
Thank you!
