### ISSUE TITLE
Add Pages to Groups GUI

### ISSUE THREAD

**Issue by Exillium313** [chris3105x/EasyPrefix#2]
GUI currently lacks the ability to expand beyond the 27 slots, a 28th gets hidden behind the "back" button. And beyond that theyll continue to fill the bottom row of the GUI.  Keep the initial 27 slots but come 28th add support for a 2nd page of Groups to be created.  Also if you use the GUI button to make the 27th Prefix, you wont be able to use it to make more as the "Add" button gets hidden beyond the back button as well.

Thanks

**Comment by chris3105x** [comment]
will be added soon

**Comment by Exillium313** [comment]
Any ETA on this?

**Comment by chris3105x** [comment]
Hey,
please excuse the late respond.
The update will come in the next few hours.
Thank you for using EasyPrefix!

Best regards,
Christian

**Comment by Exillium313** [comment]
Additional pages for groups in /ep setup work fine, but for someone who has access to all tags. /ep settings returns an error
https://pastebin.com/m38PTrPZ

Think whatever page system you made for the setup GUI needs to be added to settings GUI.

Thanks!

**Comment by chris3105x** [comment]
fixed.
Thanks!

**Comment by Exillium313** [comment]
When will the groups in /ep settings be added

**Comment by chris3105x** [comment]
Please download the newest version (1.6.4_R1)
