### ISSUE TITLE
/ep command unable to load[BUG]

### ISSUE THREAD

**Issue by ddjai-28** [chris3105x/EasyPrefix#22]
# Details
**Spigot Version:** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
/ep debug unable to load

# Expected behavior
should be loaded well

# Screenshots
![bug](https://user-images.githubusercontent.com/67776641/89132941-5fd03c00-d54a-11ea-8d5d-9ea97cad501e.PNG)
![error](https://user-images.githubusercontent.com/67776641/89132943-61016900-d54a-11ea-8b08-c7a2a653e066.PNG)

**Comment by chris3105x** [comment]
Please use Placeholderapi version 2.10.6 (https://www.spigotmc.org/resources/placeholderapi.6245/download?version=328837)

**Comment by ddjai-28** [comment]
![whatproblem2](https://user-images.githubusercontent.com/67776641/89133527-2817c300-d54f-11ea-9ca3-8b859a0538a7.PNG)
![whatproblem](https://user-images.githubusercontent.com/67776641/89133529-2948f000-d54f-11ea-86bf-dcb53f439267.PNG)
how to solve?

**Comment by ddjai-28** [comment]
why has two prefix in chat

**Comment by ddjai-28** [comment]
@chris3105x

**Comment by chris3105x** [comment]
Please set handle-chat to false in config.yml.
This happens if you have Vault and a chat plugin like EssentialsChat, Multichat, etc. installed.
