### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tmdoofking** [chris3105x/EasyPrefix#224]
# Details
**Spigot Version:** 

*please run `/ep debug` and attach a screenshot*
![image](https://github.com/chris3105x/EasyPrefix/assets/70594985/6caf248c-95dd-4395-a5a6-b7a9362d1e41)

# Describe the bug
i can type /suffix or /prefix to change my prefix without any permission
![image](https://github.com/chris3105x/EasyPrefix/assets/70594985/d7df4ee8-c8f2-45b1-9717-4f8b9ae2e936)

# Expected behavior
it will show you don't have permission

# Screenshots

**Comment by chris3105x** [comment]
Fixed.
Thank you!
