### ISSUE TITLE
This plugin is doubling the names after I updated.

### ISSUE THREAD

**Issue by ArvickC** [chris3105x/EasyPrefix#24]
# Details
**Spigot Version:** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
The player's have 2 prefixes.

# Expected behavior
To work normal with one prefix

# Screenshots
![image](https://user-images.githubusercontent.com/69405114/95685067-7af2a400-0baa-11eb-8841-9f9f852b9657.png)

**Comment by ArvickC** [comment]
![image](https://user-images.githubusercontent.com/69405114/95685144-e89ed000-0baa-11eb-8939-fb01acdc0a94.png)

**Comment by ArvickC** [comment]
@chris3105x

**Comment by chris3105x** [comment]
do you use essentials chat?

**Comment by ArvickC** [comment]
Yeah, The plugin? @chris3105x

**Comment by chris3105x** [comment]
please remove it, or set handle-chat in config.yml to false

**Comment by ArvickC** [comment]
Okay, Let me try it

**Comment by ArvickC** [comment]
Yes! It worked, Thank you!
