### ISSUE TITLE
I see everything x2

### ISSUE THREAD

**Issue by LukysGaming** [chris3105x/EasyPrefix#25]
![image](https://user-images.githubusercontent.com/49752472/98450744-88fefa80-213f-11eb-9031-bb30d7c90639.png)
![image](https://user-images.githubusercontent.com/49752472/98450752-95835300-213f-11eb-96f1-b205aa650efc.png)

**Comment by chris3105x** [comment]
Please set "handle-chat" to false in config.yml

**Comment by LukysGaming** [comment]
If i set it to false i see nothing
![image](https://user-images.githubusercontent.com/49752472/98465732-39fea700-21cb-11eb-8916-69624bf39d6c.png)

**Comment by chris3105x** [comment]
You have EssentialsChat installed. Use the placeholders or enable handle-chat and remove EssentialsChat.

**Comment by LukysGaming** [comment]
ok got it, how can i set one group can use only choosen chat colors?

**Comment by chris3105x** [comment]
Players can choose a chat color at `/ep settings`. You must give them permissions, please look at spigotmc.org.
