### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Peanutismo123** [chris3105x/EasyPrefix#31]
# Details
**1.8** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
When i setup my prefix its all ok but on the name what everybody see it says "[Yousteve123" and i dont want that i want it to say "[Youtube] steve123" same with other prefixes.

# Expected behavior
i want it to say [YouTube] steve123 not [Yousteve123

# Screenshots

**Comment by chris3105x** [comment]
Run `/ep debug` and attach a screenshot, also please send me the file groups.yml

**Comment by Peanutismo123** [comment]
![2020-11-30_12 21 38](https://user-images.githubusercontent.com/75209274/100604626-1086f600-3307-11eb-909d-60e8fc040e98.png)


There is the screenshot but i cant paste here the file groups.yml

**Comment by Peanutismo123** [comment]
ok i will send it here in zip


[group.zip](https://github.com/chris3105x/EasyPrefix/files/5615683/group.zip)

**Comment by Peanutismo123** [comment]
and it also happends only behind the name on the player in tablist and scoreboard its ok

**Comment by chris3105x** [comment]
does the chat work? Which tablist plugin do you use?

**Comment by Peanutismo123** [comment]
in chat it work too here is the tab plugin https://www.spigotmc.org/resources/tab-1-5-x-1-16-4.57806/

**Comment by chris3105x** [comment]
Please make sure you have the latest version of placeholderapi and tab!
This doesn't seem to be an issue by easyprefix, because the chat wouldn't work too.

**Comment by Peanutismo123** [comment]
ok
