### ISSUE TITLE
[BUG] Cannot disable the /color select in any way

### ISSUE THREAD

**Issue by The-Noble** [chris3105x/EasyPrefix#38]
# Details
Paper-330

https://imgur.com/a/6jJBvWg

# Describe the bug
I set the permissions so that people cannot change their own Chat Colors, but the /color select {color} still seems to work.

# Expected behavior
When the permissions are disabled for that group it shouldn't work.

# Screenshots
https://imgur.com/U4eK8II

**Comment by chris3105x** [comment]
This issue has been already introduced to us. The update will be released in a few hours.

Thank you!
