### ISSUE TITLE
Joining Text

### ISSUE THREAD

**Issue by NorthSpitz** [chris3105x/EasyPrefix#4]
Hi I just want to start by saying I really enjoy the plugin so far but  whenever I join, it says "%ep_user_prefix%NorthSpitz" and I am just wondering if there is a way to get rid of it. Attached is an image of the text
![Capture](https://user-images.githubusercontent.com/60452867/73407808-8077ba80-42b7-11ea-83be-b6f0b7b13a5a.PNG)

**Comment by chris3105x** [comment]
Hey!
Please install placeholderapi. 

regards,
Christian
