### ISSUE TITLE
[BUG] confirmation message after setting a custom prefix does not show up

### ISSUE THREAD

**Issue by ImmortalAmpharos** [chris3105x/EasyPrefix#45]
# Details
**Spigot Version: Paper RO.1-SNAPSHOT** 
![image](https://user-images.githubusercontent.com/34759737/103321374-f6702e80-49fe-11eb-9b55-f87829a4ad74.png)

*please run `/ep debug` and attach a screenshot*

# Describe the bug
The confirmation message after setting a custom prefix shows up as a blank message.

# Expected behavior
The prefix confirmation would appear, or there would be no prefix confirmation at all.

# Screenshots
![image](https://user-images.githubusercontent.com/34759737/103321401-1f90bf00-49ff-11eb-85a8-92e2a96394d5.png)

After typing anything into it, it sends the space at the bottom (no confirmation message)
![image](https://user-images.githubusercontent.com/34759737/103321419-2e777180-49ff-11eb-963f-36f7c2f84020.png)
Here are all my plugins.

**Comment by chris3105x** [comment]
Thank you!
Please [download](https://www.spigotmc.org/resources/easyprefix-gui-custom-prefixes-sql-support.44580/update?update=379186) v1.7.4.

#46
