### ISSUE TITLE
[BUG] Sending an error after enabling SQL

### ISSUE THREAD

**Issue by RodgersNetwork** [chris3105x/EasyPrefix#56]
# Details
**Spigot Version: 1.16.1** 

*please run `/ep debug` and attach a screenshot*
![image](https://user-images.githubusercontent.com/78491117/106769815-49a85300-6635-11eb-9a7f-f404542a43ed.png)

# Describe the bug

I just enabled SQL and input the details into the config for it to connect to it. When reloading the config, it just gives an error in the console. (Screenshot below)

# Expected behavior

I expected the plugin to connect to the SQL server and reload properly.

# Screenshots
![image](https://user-images.githubusercontent.com/78491117/106770080-86744a00-6635-11eb-9146-163473c73bff.png)
![image](https://user-images.githubusercontent.com/78491117/106770204-a3a91880-6635-11eb-882a-ec6ff67c5694.png)

**Comment by chris3105x** [comment]
Hello!
Thank you for the report!

Did you restart the server? A plugin reload is not recommended. Please stop and start the server.

greetings
