### ISSUE TITLE
Multiverse chat compatability

### ISSUE THREAD

**Issue by jonathanmizzi18** [chris3105x/EasyPrefix#6]
Hi,

Can you make this plugin compatible with multiverse chat to show the world that you are in?

Using this plugin breaks that multiverse feature.

**Comment by chris3105x** [comment]
Please install PlaceholderAPI.
Add one of [these ](https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-2/#multiverse-core [)placeholders] to prefix or suffix

**Comment by jonathanmizzi18** [comment]
I just tried this but it doesn't seem to work still

**Comment by chris3105x** [comment]
did you install the papi extension?

**Comment by jonathanmizzi18** [comment]
That worked thanks!

Also is there a way to make Easyprefix assign one of the groups (selected in config) on first time join?

**Comment by chris3105x** [comment]
Great!
Not necessary. New players without any easyprefix permissions use the group "default"
