### ISSUE TITLE
Back/Close button isn't working

### ISSUE THREAD

**Issue by real49N** [chris3105x/EasyPrefix#61]
# Details
**Spigot Version:** 
1.8.8
*please run `/ep debug` and attach a screenshot*
https://prnt.sc/10a5ajv

**# Describe the bug
A clear and concise description of what you expected to happen.**

I did /ep setup to check the plugin, it worked fine, but when I went into any section, groups for example and clicked around I saw the Red Rose button. When I clicked that it sent many errors into the console.

**# Expected behavior
A clear and concise description of what you expected to happen.**

I believe that it should be like a close/back button?

# Screenshots
Here is a pastebin of the console error, hope it gets fixed soon!
https://pastebin.com/QNF8Ay7J

**Comment by chris3105x** [comment]
Fixed. Thank you!
