### ISSUE TITLE
[BUG] Infinite Paging & Duplication (Settings GUI)

### ISSUE THREAD

**Issue by EnderGamingFilms** [chris3105x/EasyPrefix#7]
**Plugin Version:** 1.6.5
**Minecraft Version:**  (Paper Spigot) 1.15.2-R0.1-SNAPSHOT

**Summary:**
If you change the groups.yml file and then do <code>/ep reload</code> this will cause the settings GUI to break (however still functional). See the images below for examples. This will also cause the user to be able to page infinitely forwards or backward.

Normal
![](https://imgur.com/QDiIjC2.jpg)

After <code>/ep reload</code>
![](https://imgur.com/YEugzRp.jpg)

**Comment by chris3105x** [comment]
Thank you!
