### ISSUE TITLE
Hi, could you help me with this?

### ISSUE THREAD

**Issue by Aquamonk** [chris3105x/EasyPrefix#86]
# Details
**Spigot Version:** 1.12.2 - 1.16.5

*please run /ep debug` and attach a screenshot*
![Screenshot_1](https://user-images.githubusercontent.com/35933684/122669550-35b55600-d1be-11eb-9cf6-74ad66d50550.png)

# Describe the bug
Hi, I had all groups created in /eprefix settings > groups, when I have conected both servers with sql all groups have dissappeared, they are in the config file, but they dont appear in /eprefix settings /// because when I click on "My Prefixes", it goes to the "tags" gui, not to the "groups" gui. And tags are disabled in the config file.

# Expected behavior
When I click in My Prefixes, it should take me to the groups gui, not to the tags gui, as it happened before conecting it with sql.

# Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/35933684/122669607-6f865c80-d1be-11eb-9a26-21aef4578a85.png)

**Comment by chris3105x** [comment]
You have to create the groups again in the gui. Modifications in "groups.yml" hasn't any effect with sql enabled.

**Comment by Aquamonk** [comment]
Cool! Thank you!
