### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Yuzi1221** [chris3105x/EasyPrefix#88]
# Details
**Spigot Version:** 
1.16.5
*please run `/ep debug` and attach a screenshot*
![image](https://user-images.githubusercontent.com/57733446/123016906-fba4a980-d3a1-11eb-8ec5-0f614ce55d5c.png)

# Describe the bug
Simply no prefixes being shows and I have all the required plugins
Placeholderapi Latest
Vault Latest
EasyPrefix Latest

# Expected behavior
To show me prefixes in chat

# Screenshots
![image](https://user-images.githubusercontent.com/57733446/123017023-36a6dd00-d3a2-11eb-97ae-81d4d72fe197.png)
![image](https://user-images.githubusercontent.com/57733446/123017088-46bebc80-d3a2-11eb-905e-858687097a75.png)

**Comment by chris3105x** [comment]
Have you Essentials or EssentialsChat installed?

**Comment by Yuzi1221** [comment]
No but I had to switch to essentials and luckperms because it wasnt working
