### ISSUE TITLE
[Feature] Custom Prefix/Suffix (Permission & Commands)

### ISSUE THREAD

**Issue by EnderGamingFilms** [chris3105x/EasyPrefix#9]
**Plugin Version:** 1.6.5
**Minecraft Version:**  (Paper Spigot) 1.15.2-R0.1-SNAPSHOT

**Summary:**
Hello, I find the "custom-prefix" setting to be very useful, however, it automatically enabled the user to adjust the suffix as well, and this is something I cannot have players change.

Also, if possible, could you implement a command that just allows the user to set their prefix. Such as <code>/ep setprefix &7Some-Prefix &f</code> (alias: <code>/prefix <></code>). I find the GUI to be lacking some features that make using the custom prefix setting useless. Such as the player messing up the entire chat layout by changing the suffix.

-- Edit --
Also could you please add a command like <code>/prefix reset</code> that does what the rest button does in the Custom-Prefix GUI.

**Comment by EnderGamingFilms** [comment]
Any status on this enhancement? I would really like to see it.

**Comment by chris3105x** [comment]
Hey!
Please download the [preview](https://github.com/chris3105x/EasyPrefix/tree/master/download).
Thank you!

**Comment by EnderGamingFilms** [comment]
Downloaded it, and it appears like nothing you added is working. I see the updates to the config file, but it does not affect anything "in-game". The commands are registers but just go back to the /ep (help). Using the "settings" gui with the proper permissions (even with easyprefix.custom.suffix = false) the option to change the suffix and the prefix is still there. Also clicking on either of them will prompt the user to input their custom tag but once you enter it it will just show the "/ep help" screen again and nothing will change.

**Comment by chris3105x** [comment]
Did you try it as OP?
I added following command:
`/ep setprefix <prefix>(or _reset_)` (requires perm `easyprefix.custom.prefix)`
`/ep setsuffix <suffix>(or _reset_)` (requires perm `easyprefix.custom.suffix)`
perm  `easyprefix.custom.gui` shows the context menu in `/ep settings` (beacon)
perm  `easyprefix.custom.bypass ` disables command delay

**Comment by EnderGamingFilms** [comment]
Oh... Actually, it is working... I don't know what I did to make it not work lol.

**Comment by chris3105x** [comment]
Thank you!
Please download the final version on spigotmc (I'll upload it in the next couples of hours)
